# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'macOS-latest'

steps:
- task: UseDotNet@2
  displayName: Use .Net sdk $(DOTNET-VERSION)
  inputs:
    version: $(DOTNET-VERSION)
- task: CmdLine@2
  inputs:
    script: |
      echo "Installing maui version from" 
      
      dotnet workload install maui-android maui-ios --from-rollback-file https://maui.blob.core.windows.net/metadata/rollbacks/8.0.40.json --source https://api.nuget.org/v3/index.json
      
      # display installed workloads

      dotnet workload list
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '6.x'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Select XCode $(XCODEVERSION)"
      
      echo '##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]'/Applications/Xcode_$(XCodeVersion).app;sudo xcode-select --switch /Applications/Xcode_$(XCodeVersion).app/Contents/Developer
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*BasicAppiumSample.sln'
    feedsToUse: 'select'
    vstsFeed: '1dbc2677-9915-4987-9686-bdbd5c7dd14d'
    noCache: true
- task: CmdLine@2
  inputs:
    script: 'dotnet build -t:Run -f net8.0-android'